text = "Shokirov Muhammadaziz Hello Word !"
upperfunc = text.upper()
lower =text.lower()
captal= text.capitalize()
length = text.__len__()
print(f"Bu textimiz upper functiya yordamida har bir harf katta harfga ogirilgan: {upperfunc}")
print(f"Bu textimiz lower functiya yordamida har bir harf kichik harfga ogirilgan: {lower}")
print(f"Bu textimiz capitalize functiya yordamida  faqat bosh harf katta harfga ogirilgan: {captal}")
print(length)

num1 = int(input("birinchi son yozing:  "))
num2 = int(input("ikkinchi son yozing:  "))
print(f"bu yerda birinchi yozgan son bilan ikkinchi yozgan soni qoshilgan javobi boladi: {num1+num2}")
num1 = int(input("birinchi son yozing:  "))
num2 = int(input("ikkinchi son yozing:  "))
print(f"bu yerda birinchi yozgan son bilan ikkinchi yozgan soni ayirilgan javobi boladi: {num1-num2}")
num1 = int(input("birinchi son yozing:  "))
num2 = int(input("ikkinchi son yozing:  "))
javob = int(num1/num2)
print(f"bu yerda birinchi yozgan son bilan ikkinchi yozgan soni bolingan javobi boladi: {javob}")
num1 = int(input("birinchi son yozing:  "))
num2 = int(input("ikkinchi son yozing:  "))
print(f"bu yerda birinchi yozgan son bilan ikkinchi yozgan soni kopaytirilgan javobi boladi: {num1*num2}")
num1 = int(input("birinchi son yozing:  "))
num2 = int(input("ikkinchi son yozing:  "))
print(f"bu yerda birinchi yozgan son bilan ikkinchi yozgan soni darajaga kopaytirilgan javobi boladi: {num1**num2}")

